CREATE OR REPLACE PROCEDURE PAFISARE(P_ID IN NUMBER, P_IMG OUT BLOB) IS 
obj ORDImage;
BEGIN
    SELECT IMG INTO OBJ FROM GANDACI WHERE ID = P_ID;
    P_IMG := OBJ.GETCONTENT();
END;
/


CREATE OR REPLACE PROCEDURE PSGEN_SEMN
IS
MYIMG ORDIMAGE;
MYSIG ORDIMAGESIGNATURE;
BEGIN
    FOR I IN (SELECT ID FROM GANDACI) LOOP
        SELECT G.IMG, G.IMG_SEMN INTO MYIMG, MYSIG 
        FROM GANDACI G 
        WHERE G.ID = I.ID 
        FOR UPDATE;
        
        MYSIG.GENERATESIGNATURE(MYIMG);
        UPDATE GANDACI G
        SET G.IMG_SEMN = MYSIG
        WHERE G.ID = I.ID;
    END LOOP;
END;
/


CREATE OR REPLACE PROCEDURE PSREGASIRE (FIS IN BLOB, CCULOARE IN DECIMAL, 
                                        CTEXTURA IN DECIMAL, CFORMA IN DECIMAL, 
                                        CLOCATIE IN DECIMAL, IDREZ OUT INTEGER) IS
SCOR NUMBER;
QIMG ORDIMAGE;
QSEMN ORDIMAGESIGNATURE;
MYIMG ORDIMAGE;
MYSEMN ORDIMAGESIGNATURE;
MYMIN NUMBER;
BEGIN
    QIMG := ORDIMAGE(FIS, 1);
    QIMG.SETPROPERTIES;
    QSEMN := ORDIMAGESIGNATURE.INIT();
    DBMS_LOB.CREATETEMPORARY(QSEMN.SIGNATURE, TRUE);
    QSEMN.GENERATESIGNATURE(QIMG);
    MYMIN := 100;
    FOR I IN (SELECT ID FROM GANDACI) LOOP
        SELECT G.IMG_SEMN INTO MYSEMN FROM GANDACI G WHERE G.ID = I.ID;
        SCOR := ORDIMAGESIGNATURE.EVALUATESCORE(QSEMN, MYSEMN, 'COLOR=' || CCULOARE || 
                                                               'TEXTURE=' || CTEXTURA || 
                                                               'SHAPE=' || CFORMA || 
                                                               'LOCATION=' || CLOCATIE || '');
        IF SCOR < MYMIN THEN 
            MYMIN := SCOR;
            IDREZ := I.ID;
        END IF;
    END LOOP;
END;
/